version: "4.0"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: arzu
    ports: ["5432"]

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=arzuy1586@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on: ["postgres"]
    ports:
      ["5050:5050"]

  web:
    build: .
    ports:
      ["8000:8000"]
    depends_on: ["postgres"]
